[package]
name = "hyouga-chess"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vampirc-uci = "0.11"
tokio = {version = "1.26", features=["full"]}
rayon = "1.7"
crossbeam = "0.8"
anyhow = "1.0"
